### ISSUE TITLE
Repeat breaks when swapping two random elements repeatably

### ISSUE THREAD

**Issue by sunesimonsen** [PolymerLabs/lit-html#100]
I know it is early days, but I just want to bring this to your attention as I actually have a small example that reproduces the error: https://github.com/sunesimonsen/web-components-experiment/blob/ssimonsen/colors/colorSwap.js#L28-L37

Just clone and start the example:

```
yarn
yarn start
```

It fails after a few swaps.

You may consider use property based testing with a library like http://unexpected.js.org/unexpected-check/ to test that these methods hold up under heavy use.

If you don't find this useful, just close the issue.

Kind regards
Sune

**Comment by justinfagnani** [comment]
Can you try out #102 and see if it fixes the problem?

**Comment by sunesimonsen** [comment]
I'll do that, thanks.

**Comment by sunesimonsen** [comment]
@justinfagnani it seems slightly more solid, but it still breaks after 3 or 4 swaps. I can try to make a reproducing test case if you like?

**Comment by justinfagnani** [comment]
@sunesimonsen that would be great, thanks!

**Comment by sunesimonsen** [comment]
@justinfagnani I added a PR with two minimal failing tests https://github.com/PolymerLabs/lit-html/pull/108 I don't have time right now to try to fix the actual problem, but the tests might help track it down.

**Comment by justinfagnani** [comment]
This was fixed by #161
