### ISSUE TITLE
Use Case Question: could nesting templates support this...?

### ISSUE THREAD

**Issue by rchrdnsh** [PolymerLabs/lit-html#101]
So, I'm running into a few issues with the templating in the framework I'm using currently (vue), and I'm wondering if lit-html will be able to support this particular use case.

So, I have this data, and some of it can be serialized, while some of it cannot:

```javascript
Article: {
  title: `The Title of the Article.`,
  subtitle: `The subtitle`,
  image: require(`the-cover-image-of-the-article.jpg`)
  category: `category`,
  content: html`
    <h1>First Heading</h1>
    <p>Some words about the first heading</p>
    <h2>A sub-heading</h2>
    <p>Some words in relation to the sub-heading</p>
    //moar content...
    `
```

...where part of the data can be serialized into key: value pairs because every article will have a title, subtitle, etc...but part of the data cannot be serialized because the structure of the content, or body, of each article is different, as said structure is inherently defined by the content of each individual article itself. One article will have 15 paragraphs, while another will have 20, etc... The fact that all articles have content can be serialized, but not the structure of the content itself. sooooo...

in a .vue component, injecting this kind of data requires the v-html directive, like so:

```javascript
<template>
  <div>
    <h1>{{ article.title }}<h1>
    <h2>{{ article.subtitle }}</h2>
    <div v-html="article.content">
      {{ article.content }}
    </div>
```

...and all of the content of the article is rendered into the component with it's inherent structure intact.

This is all well and good, until scoped styles come along, meaning that the content itself is apparently being rendered outside of vue, so vue cannot scope the tags in the content using it's scoping mechanism, so I end up losing a big aspect of using something like vue in the first place. I can make it work with global styles, but I would really like it to work with scoped styles. sooooo...

I'm thinking that nested templates in lit-html and shadow DOM in general might solve this, maybe looking something like this:

```javascript

//dunno the syntax well for vanilla (or not vanilla) web components all that well yet...

import { article } from 'article.js'

class SuperUltraMegaSexyArticle extends CoolLitMixin(HTMLElement) {

//dooz the shadow DOM (dunno the syntax)

let title = `article.title`
let subtitle = `article.subtitle`
let content = `article.content`

render () {
  return html`
    <h1>${this.title}</h1>
    <p>${this.body}</p>
    <div>${this.content}</div>
  `
  }

}
```

...and the content that is injected will be a nested template literal template from the `article.js` file, or form a JSON6 file, or whatever...and all templates and nested templates inside the component will be scoped to the shadow DOM and so can be styled with styles that don't leak in or out.

Does this make sense? Is this kind of thing possible? I got excited for lit-html and HyperHTML for this very reason, and I just kinda want to know that it's a thing that can be done, and thus, still be excited about :-)

R

**Comment by justinfagnani** [comment]
Hey @rchrdnsh 

So, if I understand correctly, are you asking if you can bind HTML content into a template?

If so, the answer is yes with the `unsafeHTML` directive:

```js
import {html, render} from 'lit-html/lit-html.js';
import {unsafeHTML} from 'lit-html/lib/unsafe-html.js';

render () {
  return html`
    <h1>${this.title}</h1>
    <p>${this.body}</p>
    <div>${unsafeHTML(this.content)}</div>
  `;
}
```

This will just work with native Shadow DOM, as the shadow root applies all the necessary scoping.

For ShadyDOM/ShadyCSS, once we add the lit-html/ShadyCSS integration this will also just work, because ShadyCSS notices new DOM appended into a scope and sets up the scoping classes automatically.

Now this part:

> ...and the content that is injected will be a nested template literal template from the article.js file, or form a JSON6 file, or whatever...and all templates and nested templates inside the component will be scoped to the shadow DOM and so can be styled with styles that don't leak in or out.

sounds like you might be asking about including a lit-html template inside your _data_. This is possible by using `new Function()` cleverly, but it's not CSP compliant. I can give some guidance here if this is what you're asking about.

**Comment by rchrdnsh** [comment]
yes, that is what I am asking...I cannot figure out any other way of storing content whose structure is inherently defined by the content that it is structuring, and also how to serve that content from one file to another and still maintain the styling and safety benefits that come with content that can be statically structured and therefore, serialized.

Basically, as I currently see it, most templating libraries, frameworks, and languages today excel at partially dynamic templates, meaning a template with static, serialized structure, but dynamic data. I'm trying to figure out how to make fully dynamic templates, where the template can accept dynamic content that requires a dynamic structure as well, like the contents of an article, for example, where the structure of the article is inherently defined by it's contents, and cannot easily be decoupled.

I really like the idea of being able to create a component with scoped styling and logic, that is also able to accept partially and fully dynamic templates at the same time and nest them infinitely, while maintaining safety throughout, hence, no unsafe html. I know where the html is coming from, it is not user generated at run time, and could therefore be sanitized properly?

I am also relatively new to app development in general, self taught, and ignorant of many things. I do not know what CSP is, for example, although I will research it. Also, it seems to me that many app developers do not necessarily look at app development from the content creators perspective, hence why there does not seem to be a well established solution for fully dynamic templates, only partially dynamic templates. As a content creator first, I have found this to be quite frustrating, but I am probably ignorant of much information and solutions that exist already that might simply be hard to come by or out of my conceptual grasp at the moment.

Anyway, any assistance or guidance that you are willing to share will be greatly appreciated :-)

Thank you XD

R

**Comment by justinfagnani** [comment]
Hey @rchrdnsh sorry I didn't get back sooner. Just wanted to drop in a snippet on how you can create lit templates dynamically:

```ts
import {html, render} from '../lit-html/lit-html.js';

function createLitTemplate(template: string) {
  // Template strings might contain characters that interfere with JavaScript parsing.
  // This is a crude and mostly wrong way to handle some of them
  // TODO: better encoding/decoding!
  const decodedTemplate = template
    .replace(/&amp;/g, '&')
    // .replace(/</g, '&lt;')
    .replace(/\\/g, '\\\\')
    .replace(/\\\$/g, '\$')
    .replace(/`/g, '\\`');
  // Wrap the user's string in a template literal
  const templateContent = `return html\`${decodedTemplate}\`;`;
  const renderFunction = new Function('html', 'data', templateContent).bind(html);
  return renderFunction;
}

const template = createLitTemplate(userTemplate);
render(template(data), document.body);
```

**Comment by rchrdnsh** [comment]
Thank you JF, no worries :-) I understand literally 0% of that right now, but I'll spend some time trying to wrap my head around it.

Thank you again :-)

**Comment by justinfagnani** [comment]
Of course! Feel free to reopen or reach out on the #lit-html channel on Polymer slack if you have more questions.
