### ISSUE TITLE
Iterable cache isn't always set correctly

### ISSUE THREAD

**Issue by 43081j** [PolymerLabs/lit-html#106]
It seems there's a bug in the way iterables are rendered.

Currently this happens:
* Render 5 TemplateResult instances
* All 5 render correctly
* Render 1 TemplateResult instance (same template, new values)
* 1 TemplateResult is updated, 4 DOM nodes are [removed](https://github.com/PolymerLabs/lit-html/blob/9d6f581f77533cb47783d0271d6d968b1f7690de/src/lit-html.ts#L418)
* Render 5 TemplateResult instances
* `_previousValue` _still_ contains 5 instances, all 5 are [updated](https://github.com/PolymerLabs/lit-html/blob/9d6f581f77533cb47783d0271d6d968b1f7690de/src/lit-html.ts#L391)
* *4 new nodes are not appended*, so 1 is rendered and the remaining 4 which were previously removed never return

This seems to be because `_previousValue` is not re-computed when the clear() call runs (when extra DOM nodes are removed). So in future renders, lit-html believes 5 nodes still exist (they don't, only 1 is in the dom tree at this point).

**Comment by justinfagnani** [comment]
Thanks for the report! I'll get this fixed in the next release
