### ISSUE TITLE
Edge-Case: Using lit-html in a typescript project may cause compiler error. (resolved)

### ISSUE THREAD

**Issue by daflair** [PolymerLabs/lit-html#107]
**Update:** (resolved)

I did some testing and found that `"noImplicitAny": false` in `tsconfig.json` causes this unexpected behaviour and surprisingly setting it this option to true seems to be assume that `any[]` is a fact and does not complain about it being an implicit any.

**Typescript Issue**: [Microsoft/typescript](https://github.com/Microsoft/TypeScript/issues/18687).

----

https://github.com/PolymerLabs/lit-html/blob/9d6f581f77533cb47783d0271d6d968b1f7690de/src/lit-html.ts#L150

I'm currently working on an experimental with a TSX to lit transformer using **TypeScript 2.5.2** and I keep running into some issues related to the line above.

It is **not a serious issue** and I am not sure if it is caused by my own TypeScript setup or due to recent (potentially breaking) changes in TypeScript.

TypeScript seems to favour checking `lit-html.ts` in my setup and since type checking for lit-html and my project are configured differently it throws (here's my pretty print tsc output):

```log
199           nodesToRemove.push(node);
                                 ~~~~
../../node_modules/lit-html/src/lit-html.ts(199,30): error TS2345: Argument of type 'Element' is not assignable to parameter of type 'never'.


207       n.parentNode!.removeChild(n);
            ~~~~~~~~~~
../../node_modules/lit-html/src/lit-html.ts(207,9): error TS2339: Property 'parentNode' does not exist on type 'never'.
```

In any case, I've noticed that recently TypeScript complains about array items when the array's variable is not typed  and is initialized with an empty array:
```ts
  let array = [];
  array.push(1); // error: 1 is not never;
```

TypeScript (under certain conditions that I did not bother testing) doesn't infer `any[]` as the type of a `never[]` and instead seems to assume that people like their arrays to actually hold nothing.

This is not a lit-html issue but can I recommend adding a type annotation like:
```ts 
  let array: number[] = []; // append as number[] or initializing with any number also works.
``` 

and, in case of the line in `lit-html.ts`, consider: 
```ts
  const nodesToRemove: any[] = []; // this will do the trick.
``` 

Thanks!

**Comment by justinfagnani** [comment]
Adding the type annotation is fine. Want to make a PR?

**Comment by daflair** [comment]
Actually, since it is really more of a TypeScript edge-case, I think this thread is a good reference for anyone who hits the same snag.

---

# The summary

## Don't Do This:

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": false
  }
}
```

## Or else you have to do this

```ts
  let array: any[] = [];
```

Since both strict and noImplicitAny false make it impossible for TypeScript's type-system to make the assumption about your empty array that never implies any.

---

I think your code should not change, those settings are likely to cause breaks in a lot of places for anyone using them.

**Comment by justinfagnani** [comment]
Good to know. I've ended up typing the array as `Node[]` in a recent PR anyway.
