### ISSUE TITLE
Tests don't run in Firefox, IE, Edge

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/lit-html#111]
I get for example this result in latest Firefox
```
0 passing tests 
test suite passed
Evaluated 0 tests in 16ms.
```

PS: using polyserve and going to http://localhost:8081/test/

**Comment by JanMiksovsky** [comment]
@daKmoR I see all unit tests pass in Firefox. What problem do you see?

**Comment by daKmoR** [comment]
they do run now :)
