### ISSUE TITLE
IE11 Limitations

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/lit-html#113]
After https://github.com/PolymerLabs/lit-html/pull/112 or something similar gets merged IE11 works pretty nice :)

Currently there are some limitations

1) Last node can't be a node with a variable
```
// works in IE11
return html`
	<h2>${header}</h2>
	<p>ending</p>
`;

// does not work in IE11
return html`
	<h2>${header}</h2>
`;
````
2) You need a polyfill for template tag and ES6 Symbols
=> so this should be somewhere noted

3) So far no ShadyCSS support

**Comment by justinfagnani** [comment]
I think we have multiple issues open on IE now, we can just keep one.
