### ISSUE TITLE
Long term vision

### ISSUE THREAD

**Issue by LarsDenBakker** [PolymerLabs/lit-html#12]
As a long time user of Polymer, this project expresses exactly what I feel is missing from our toolbox when building apps in Polymer.

What's the long term vision for this, and it's relation to Polymer? Is it something that will be officially supported? I'd hate to see this end up gathering dust.

**Comment by justinfagnani** [comment]
At this point we're still experimenting and benchmarking.

Regarding Polymer, Polymer 2.0 is organized in a way that lets you pick and choose the features to use, and only "pay" for those features, not the others, via mixins. It's possible to use Polymer's sugar and property change management with alternate, or even no, templating systems. Monica gave a good talk that touches on this at this year's I/O: https://www.youtube.com/watch?v=zfQoleQEa4w

**Comment by justinfagnani** [comment]
I think this is answered as well as can be for the moment. We'll know more as the project matures!

**Comment by LarsDenBakker** [comment]
Indeed, thanks. I will keep keep track of the project:)
