### ISSUE TITLE
svg support not added to the npm registry

### ISSUE THREAD

**Issue by jaihindhreddy** [PolymerLabs/lit-html#125]
I added lit-html with yarn, got 0.6.0 but doesn't have svg export. Is there a reason why 0.6.0 is different in the npm registry and here?

PS: I'm a n00b in today's javascript world. Please point it out if it's just me. Thanks.

**Comment by SebastianFlo** [comment]
Noticed the same

**Comment by jaihindhreddy** [comment]
Closing this. Support being added in https://github.com/PolymerLabs/lit-html/pull/127/commits/662bb47e58ec1c87de64d2b0f573a96860bf3238 as a part of 0.7.0
