### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jaihindhreddy** [PolymerLabs/lit-html#126]
I cannot get the clock demo to work. Initial render works fine. But it does not update.

**Comment by justinfagnani** [comment]
@jaihindhreddy there are a few bugs that cropped up with a change in how binding placeholders worked. They're fixed in pending PRs, so the demo should be working with the next release, which I'll try to get out tomorrow.

Thanks for the report!

**Comment by justinfagnani** [comment]
The demo is working in 0.7.1, and I have a version up on CodePen too: https://codepen.io/justinfagnani/pen/mBQpqJ
