### ISSUE TITLE
Rerendering a node part causes the node to be removed, then re-added

### ISSUE THREAD

**Issue by JanMiksovsky** [PolymerLabs/lit-html#128]
If a node or array of nodes is passed to a template, the nodes are rendered as expected — but subsequent renders cause the nodes to be removed and then re-added each time, which is inefficient.

See http://jsbin.com/fomepuj/edit?html,output. Clicking the Update button shows the DOM updating (the nodes briefly flash color in Chrome DevTools), even though the same nodes are being passed in each time. Since no data is actually changing, I'd expect subsequent renders to not update the DOM.

In `NodePart.setValue`, it looks like the `value instanceof Node` case could be optimized by skipping the update if `value === this._previousValue`.

Is the current behavior intentional? If not, I'm happy to submit a fix.

**Comment by gdi2290** [comment]
here's a workaround and I created a PR
http://jsbin.com/nahoyatoxe/edit?html,output
