### ISSUE TITLE
event handlers doesn't work if they are not in separate html tagged function

### ISSUE THREAD

**Issue by Hotell** [PolymerLabs/lit-html#133]
let's say we have a `Result` function

```js
import { html } from 'lit-html/lib/lit-extended'

export const Result = ({ result }) => html`
 <div class="result">
    <div>
      <a href=${result.html_url} target="_blank">
        ${result.full_name}
      </a>
      🌟<strong>${result.stargazers_count}</strong>
    </div>
    <p>
      ${result.description}
    </p>
    ${Button({ onClick: e => console.log(e), children: 'Click Me' })}
    <button on-click=${e => {
      console.log(e)
    }}>Remove</button>
  </div>
`

const Button = ({ onClick, children }) => html`
   <button on-click=${onClick}>${children}</button>
`
```

This won't create an event handler and breaks rendering
```
<button on-click=${e => {
      console.log(e)
    }}>Remove</button>
```
If there is just one element, it works ok

Workaround is to create separate functions for rendering but that can get annoying pretty quickly

![image](https://user-images.githubusercontent.com/1223799/31491869-10ed51c4-af49-11e7-81bc-37725d7f749b.png)

demo: 
https://codesandbox.io/s/m5lkpjm5mj

**Comment by Hotell** [comment]
omg, my bad, need more sleep I guess! :D

quotes were missing...
```diff
-<button on-click=${e => {
    console.log(e)
-  }}>Remove</button>
+<button on-click="${e => {
    console.log(e)
+  }}">Remove</button>
```

**Comment by obedm503** [comment]
if I'm not mistaken, quote are (or should be) optional

**Comment by RayBenefield** [comment]
I actually agree with @obedm503, @Hotell . The quotes should be optional if possible. From my testing, if the event handler is the first substitution, it works without quotes, however if it is after any other substitution it requires quotes to work. This inconsistency should be fleshed out.

**Comment by jridgewell** [comment]
This  was fixed in latest master.

**Comment by RayBenefield** [comment]
Awesome thanks for the heads up @jridgewell ... I'm working off `0.7.1` so I was unaware. 👍
