### ISSUE TITLE
How to use lit-html from CDN

### ISSUE THREAD

**Issue by richardanaya** [PolymerLabs/lit-html#141]
Could you provide an example of using lit-html from CDN please

**Comment by richardanaya** [comment]
Perhaps you can add umd minfied output to build?

**Comment by nicolasparada** [comment]
You can import it from a `<script type=module>`:
```js
import { html, render } from 'https://unpkg.com/lit-html@0.7.1/lit-html.js'
```
That since Safari, Chrome and Edge do support modules ✨

**Comment by richardanaya** [comment]
Would it not be preferable to have a babelified minified version that can be used by more browsers to play with?

module seems very new

**Comment by nicolasparada** [comment]
I think "babelifying" it's of users land. Like when you add polyfills and that sort of thing.
I think that the way lit-html is distributed is the right way, but maybe a minified version could be handy.

**Comment by richardanaya** [comment]
It is your project, I think it just does not lend itself well to people sharing code on code pen:

Observe: https://codepen.io/kenbrown/pen/xXjQoZ

How the code must be put in html

It looks worse on jsfiddle

Not to mention browsers without type=module

**Comment by arko-loves-to-code** [comment]
You can only provide styles in lit-html using 
1. style tags as ${ } do not interfere with { } of CSS and
2. using inline styling

@richardanaya I modified your pen on codepen here:

https://codepen.io/the_guy_with_pajamas/pen/wypXrm

**Comment by justinfagnani** [comment]
```
import { guard } from 'https://unpkg.com/lit-html/directives/guard.js?module';
```

**Comment by jikkuatwork** [comment]
I really think lit should include CDN link examples on home page. I have seen this project before and assumed this is another bundler madness. 

I was running around multiple sites now for an easy copy/paste CodePen start. Despite this being built with such an interesting design goal, its very sad to see the npm install lit command at the front page like all other frameworks!

There is not even a mention of a CDN link in the homepage!

**Comment by justinfagnani** [comment]
@jikkuatwork commenting on long-closed issues isn't a great way to raise a point. Unless someone sees the notification, these comments are to easily missed.

Did you try the CDN bundles references in the Getting Started page? https://lit.dev/docs/getting-started/

re: npm. Lit is comprised of many packages. There is no single bundle that would be suitable for everyone. npm is great for distributing interdependent packages. There is nothing at all sad about using it. It does the job we need it to do.

**Comment by jikkuatwork** [comment]
Yes, I know thats the typical opinion. And I know you are right too, for many such a system might be ideal.

I stumbled on this expecting a zero bundling workflow. Sorry to bother, best wishes. I think Petite Vue is the solution for me after all.
