### ISSUE TITLE
Async Iterable Support

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/lit-html#15]
Now that there's a PR for Promises (#14), we should think about async iterables.

Async iterables would allow for very easy to express incrementally rendered lists. To control how fast items are rendered into the list, just control how values are resolved into the iterable. Streaming server responses could also easily be rendered incrementally.

The part that's trickier over Promise support is that we can't just call `setValue()` in the callback anymore, we have to append new item Parts, and might have to give up on part reuse if it's too complex.

**Comment by surma** [comment]
Additional use-case that I am running into right now: You could schedule the async iterator with `requestIdleCallback` to make sure the main threads stays responsive (think: Rendering 10k new children).

**Comment by KeithHenry** [comment]
I thought `requestIdleCallback` fired after the current frame has been drawn, at which point it should probably wait for the next frame before rendering anything else? Would it also need a `requestAnimationFrame`?

**Comment by gdi2290** [comment]
`requestIdleCallback` is fired when the microtasks/macrotasks queue is empty and after `requestAnimationFrame` as you mentioned
https://developers.google.com/web/updates/2015/08/using-requestidlecallback
![](https://developers.google.com/web/updates/images/2015-08-27-using-requestidlecallback/frame.jpg)

```js
function processPendingElements (deadline) {

  // If there is no deadline, just run as long as necessary.
  if (typeof deadline === 'undefined')
    deadline = { timeRemaining: function () { return Number.MAX_VALUE } };

  if (!documentFragment)
    documentFragment = document.createDocumentFragment();

  // Go for as long as there is time remaining and work to do.
  while (deadline.timeRemaining() > 0 && elementsToAdd.length > 0) {

    // Create the element.
    var elToAdd = elementsToAdd.pop();
    var el = document.createElement(elToAdd.tag);
    el.textContent = elToAdd.content;

    // Add it to the fragment.
    documentFragment.appendChild(el);

    // Don't append to the document immediately, wait for the next
    // requestAnimationFrame callback.
    scheduleVisualUpdateIfNeeded();
  }

  // Check if there are more events still to send.
  if (elementsToAdd.length > 0)
    scheduleElementCreation();
}
```
```js
 function scheduleVisualUpdateIfNeeded() {

  if (isVisualUpdateScheduled)
    return;

  isVisualUpdateScheduled = true;

  requestAnimationFrame(appendDocumentFragment);
}

function appendDocumentFragment() {
  // Append the fragment and reset.
  document.body.appendChild(documentFragment);
  documentFragment = null;
}
```
