### ISSUE TITLE
Understanding re-rendering using lit-html

### ISSUE THREAD

**Issue by richardanaya** [PolymerLabs/lit-html#150]
I'm trying to understand the implications of lit-html's render process. Typically, I imagine a component that is re-rendering it's contents again and again. Re-render appears to blast away the content's of it's target element everytime. Wouldn't this pose a difficulty for the statefulness of child elements? Am I wrong in observing that lit seems optimized only for the copying of templates, but not for the maintenence of child state.

**Comment by justinfagnani** [comment]
lit-html does not re-render the static portions of a template, only the dynamic parts, and only those whose value has changed. lit-html is highly optimized for fast updates with minimal mutations.
