### ISSUE TITLE
Merge lit-extended into lit-html, property first

### ISSUE THREAD

**Issue by nicolasparada** [PolymerLabs/lit-html#152]
lit-html could check if the property exists in the element and try to set it:
```js
if (propertyName in element) {
  element[propertyName] = value
}
```
With a fallback to setting the attribute. This is what Preact does.
Also, the declarative event handling is quite used. It should be just merged into.

This simplifies the API avoiding the confusion with lit-extended and the attribute/property thing:
```html
<element foo$="bar">
```

**Comment by richardanaya** [comment]
I don't think this is a good idea. lit-html is built to be extensible so you can implement these special logics yourself. Not make them a default for all users of lit-html.

**Comment by justinfagnani** [comment]
Explicit is much better than this kind of checking, which can fail in many ways, especially over time as element APIs evolve. If you want this kind of thing you can implement a part callback like @richardanaya suggests.
