### ISSUE TITLE
Can we define 'constant' template parts that don't need to be 'tracked'?

### ISSUE THREAD

**Issue by jovdb** [PolymerLabs/lit-html#158]
Simple example:
```
const primaryThemeColor = "blue";

function render(title: string) {
  return html`<h1 style="color: ${primaryThemeColor}'>${title}</h1>`;
}
```
Here we want to add styling, and we know this will not change during the application lifetime.
A larger application could use [TypeStyle](https://typestyle.github.io) to add styling into the HTML.

Can we inform lit-html that a part doesn't need to be tracked/updated or are these effects negligible?

**Comment by justinfagnani** [comment]
The effects are usually negligible, but there is already a request for this already in #78.
