### ISSUE TITLE
add shadowRoot as allowed type for the render-container 

### ISSUE THREAD

**Issue by filipbech** [PolymerLabs/lit-html#159]
Maybe I'm missing something, but shouldn't the container-argument in the render-method also accept the type ShadowRoot? 
For the web-components usecase I think this would be a pretty normal usecase? or am I missing something?
https://github.com/PolymerLabs/lit-html/blob/master/src/lit-html.ts#L83

I can submit a PR if you'd like?

**Comment by justinfagnani** [comment]
This already works. A ShadowRoot is a DocumentFragment. Just do:

```ts
render(templateResult, this.shadowRoot);
```

**Comment by filipbech** [comment]
You are right, I was dealing with a null situation... sorry

**Comment by justinfagnani** [comment]
No worries!
