### ISSUE TITLE
Suggestion - alternative way to render

### ISSUE THREAD

**Issue by nikhilk** [PolymerLabs/lit-html#167]
I created a similar suggestion issue on hyperHTML, so only fair I pass this along here too :)

From example, I see this:

    import {html, render} from 'lit-html';
    const helloTemplate = (name) => html`<div>Hello ${name}!</div>`;
    render(helloTemplate('Steve'), document.body);

Would this make sense and be possible?

    import {html} from 'lit-html';
    const helloTemplate = (name) => html`<div>Hello ${name}!</div>`;
    document.body.render(helloTemplate('Steve'));

Specifically looking for a `render` method hanging off of HTMLElement.

And of course hoping this sort of HTMLTemplate and render method become a standard/built-in thing some day in the future.

**Comment by web-padawan** [comment]
Have you read the [template instantiation](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Template-Instantiation.md) proposal? It seems to be the way to standartize some concepts which `lit-html` represents.

**Comment by justinfagnani** [comment]
I think we generally want to avoid money patching the DOM outside of polyfills. Say both lit-html and hyperHTML try to add a render() method to Element. Who wins?

Having a render method expected in lit-html avoids the collision and allows for other indirections, like wrapping render for special behavior, but only in one part of a program, not globally.

Thanks for the suggestion though.

**Comment by nikhilk** [comment]
I am fine if you close it - this was a suggestion. But as far as "who wins" question, I think it should be controlled by the app developer who decides which library to include, and eventually hopefully this becomes a standard, so any library adding it would add after checking - effectively a polyfill. Isn't your question "who wins" the same when it comes to polyfills that libraries add?

**Comment by justinfagnani** [comment]
A polyfill would be implementing a standard, with an expected argument type. lit-html's render function takes a lit-html specific value in TemplateResult. Another library may have another opinion on what arguments to take.

Patching HTMLElement is a global operation, so only one patch can be active. Right now you can use both lit-html and hyperHTML in the same page, but with a global patch you couldn't. This is a severe problem when you might have web components that use either on the same page.

**Comment by prasannavl** [comment]
Stumbled into this searching for something. So, thought I'll just add it here.

@nikhilk - Try taking `icomponent` (https://github.com/prasannavl/icomponent) for a spin. It's gets very close to what you expect, but with custom-elements, so monkey-patching and is as bare as you can possibly get.

It basically let's you do this:

```js
import { Component, Renderer } from "icomponent";
import { html, render } from "lit-html";

Renderer.render = (c) => render(c.view(), c.getRenderRoot());

class App extends Component {
  view() {
        return html`
        <div>Hello world!</div>
        `;
    }
}

customElements.define("x-app", App);
```

Or, your own render (from the README):

```js
import { Component, Renderer } from "icomponent";
import { html, render } from "lit-html";

class LitHtmlComponent extends Component {
   // Override this function to change any rendering logic.
   // This can use hyperhtml, React, Vue, or any custom logic
   // as desired.
    createRenderer() {
        // The icomponent-lit does the exact same thing conceptually,
        // just in a slightly more optimized way.
        return new Renderer(this, () => render(this.view(), this.getRenderRoot()));
    }
}

class App extends LitHtmlComponent {
    view() {
        return html`
        <my-nav></my-nav>
        <div>Hello world!</div>
        `;
    }
}
```

Long story short, I think `lit-html` exposes just enough as it should without stepping on the shoes of component, or lifecycle which are better handled outside of it.
