### ISSUE TITLE
Support Angular-style attributes

### ISSUE THREAD

**Issue by bgotink** [PolymerLabs/lit-html#172]
I'm trying to use angular-style attributes for property/event binding using a custom `render` extension, but I run into an error when trying to call `html` with that syntax.

```js
import {html} from './path/to/lit-html/lit-html.js';

html`<some-element [prop]=${5} (click)=${() => alert('clicked!')}></some-element>`;
```

```
  Cannot read property '1' of null
    <unknown> at   new Template at /components/lit-html/lit-html.js:172:0
    <unknown> at         litTag at /components/lit-html/lit-html.js:43:0
    <unknown> at           html at /components/lit-html/lit-html.js:31:0
```

The `lastAttributeNameRegex` used at [`src/lit-html.ts#L209-210`](https://github.com/PolymerLabs/lit-html/blob/eeafa95c820672ec95231afbc5861d1755d46457/src/lit-html.ts#L209-L210) doesn't match because of the `[]` and `()` in the attribute names.

I've seen comments in #168 that this regex might disappear in the future ([link](https://github.com/PolymerLabs/lit-html/pull/168#discussion_r148941842)). Is this future coming soon or would you accept a PR that adds `[]()` to `lastAttributeNameRegex`?

**Comment by jridgewell** [comment]
I can't think of a way to remove it without reverting to a FSM, which will likely be slower. HTML5 [defines](https://www.w3.org/TR/html5/syntax.html#attributes-0) attributes as anything but a few characters, so we could match that with a few of complicated character classes:

```js
/[^\0-\x1F\x7F-\x9F \x09\x0a\x0c\x0d"'>=/]+[ \x09\x0a\x0c\x0d]*=[ \x09\x0a\x0c\x0d]*(?:[^ \x09\x0a\x0c\x0d"'`<>=]*|"[^"]*|'[^']*)$/

**Comment by justinfagnani** [comment]
Putting together the some tests for this now
