### ISSUE TITLE
lit-html django integration?

### ISSUE THREAD

**Issue by kamranhossain** [PolymerLabs/lit-html#190]
Is lit-html working in django instead of django template engine? Or how we integrate lit html in django?

**Comment by justinfagnani** [comment]
Django is a server-side framework. I'm not sure how lit-html fits in with that. What exactly are you thinking about?

**Comment by justinfagnani** [comment]
I don't think lit-html needs to have much of an opinion on integration with a server framework, at least until there are some server-side implementations of lit templates. I'm going to close this for now.
