### ISSUE TITLE
Atom syntax highlighting

### ISSUE THREAD

**Issue by ShavidzeT** [PolymerLabs/lit-html#191]
**There is no support yet syntax highlighting on atom editor.**

What do you plan for the near future?

Will you support syntax and some stuff by yourself or are you waiting for contributors?

**Comment by kenchris** [comment]
The one MS made for VSCode should work for Atom and Sublime.

**Comment by kenchris** [comment]
https://github.com/Microsoft/typescript-lit-html-plugin

**Comment by TimvdLippe** [comment]
Hm it works without any plugin in Atom for me (syntax highlighting set to JavaScript):
![image](https://user-images.githubusercontent.com/5948271/33332014-6defffb8-d463-11e7-90c1-a67dc5ac1001.png)

It correct highlights if you use `html` as the name of the tagged template literal. Could you post the snippet that is not highlighting for you?

**Comment by ShavidzeT** [comment]
My snippet:
<img src="https://i.imgur.com/atPa0ma.png" width="600px" />

**Comment by TimvdLippe** [comment]
Hm, I am running Atom 1.22.1 and when I input this in a plain JavaScript file I get:
![image](https://user-images.githubusercontent.com/5948271/33342169-7477490e-d481-11e7-9fe4-d0867b4ebb36.png)

**Comment by ShavidzeT** [comment]
@TimvdLippe I'm on 1.22.0 and upgrading now

**Comment by ShavidzeT** [comment]
Found the problem.
I .js files was highlighted by babel es6 javascript and hadn't any .babelrc in project, when I move babel to js, problem solved 🚀 🎸  💯 ✌️

**Comment by lastmjs** [comment]
But wait, it doesn't work for TypeScript files in Atom
