### ISSUE TITLE
PropertyPart.setValue() mis-handles 'data-name' type properties.

### ISSUE THREAD

**Issue by depeele** [PolymerLabs/lit-html#194]
When setting the value of a "property", if the name targets the `dataset` of the element (e.g. 'data-id' or, I suspect any name of the form 'attr-name'), the act of setting actually drops the value.

In the following example, none of the target `li` elements receive a `data-id` attribute:
```
html`
<ul>
  ${repeat( this.getAccounts(), (account) => html`
    <li data-id="${account.id}">${account.name}</li>
  `)}
</ul>
`;
```

In `PropertyPart.setValue()`, the incoming value is *always* assigned directly to the element:
```
85:    (this.element as any)[this.name] = value;
```

Since for the above example, `this.name` is 'data-id', setting the property directly causes it to be lost.

I would propose something like:
```
if (this.name.indexOf('-') >= 0) {
  this.element.setAttribute( this.name, value );
} else {
  (this.element as any)[this.name] = value;
}
```

**Comment by daKmoR** [comment]
if you wish to set an attribute I would recommend using lit-extended with the following syntax
`<li data-id$="${account.id}">${account.name}</li>`

should work just fine :)

**Comment by depeele** [comment]
Nice to know!

Is that something special with `lit-extended`?

The documentation for `lit-html` suggests you should use:
`<li attr="${value}">...</li>`

Is the difference documented somewhere?

Thanks for the pointer!

**Comment by daKmoR** [comment]
hmm didn't found any documentation myself...
u sure you don't use lit-extended? as with just lit-html I think it only sets attributes?

in lit-extended you can use
`<li something="${var}">`
to set an property

and 
`<li something$="${var}">`
to set an attribute

as you probably don't want to set an property for `li` I guess you want the `$=`

**Comment by depeele** [comment]
You were correct, I am using `lit-extended` but the only documentation I have found is for `lit-html`, which I assumed also applied to `lit-extended`.

I remember this same syntax from Polymer but didn't realize it applied to `lit-extended`.

Thanks for pointing out the difference!

**Comment by daKmoR** [comment]
if that worked out for you could you pls close this issue :) thx
