### ISSUE TITLE
Not getting the same TemplateResult for same values

### ISSUE THREAD

**Issue by kenchris** [PolymerLabs/lit-html#196]
Calling html`` with the same template string should return the same TemplateString, so that render will only re-render if values have changed. While debugging the fiber demo, which renders in a rAF, I wondered why filip's optimization made any difference.

It now seems that different TemplateString is returned for the same template even with same values:

https://github.com/filipbech/lit-element-fiber-demo/issues/2#issuecomment-345672316

**Comment by kenchris** [comment]
I see that the TemplateResult is not the same, but the template is, so I can make such an optimization in a base class like my LitElement (lit-html-element)

```
    renderCallback() {
        const result = this.render();
        if (this.lastResult && result.template === this.lastResult.template) {
            const lastValues = this.lastResult.values;
            const newValues = result.values;
            const isSameValues = (lastValues.length == newValues.length) && lastValues.every((value, index) => {
                return value === newValues[index]; 
            });
            if (isSameValues) return;
        }

        this.lastResult = result;

        render(result, this.shadowRoot);
    }
```

I wonder if that is the way to go, or we if we can have such an optimization inside lit-html itself.

**Comment by justinfagnani** [comment]
TemplateResult isn't support to be the same for any evaluation of ``html````, it's a fresh object every time. It's a simple object though and generally requires very, very little work to construct since it only contains a reference to the template and the values from the template literal interpolations.

That optimization you have shouldn't really make much of a difference. It's very close to what lit's doing internally.

mid-reply realization: The dirty-checking optimization we do in NodePart here: https://github.com/PolymerLabs/lit-html/blob/master/src/lit-html.ts#L445 should be ported to AttributePart, in here: https://github.com/PolymerLabs/lit-html/blob/master/src/lit-html.ts#L419

I'll open a new issue for that and close this one.
