### ISSUE TITLE
IE: importNode doesn't clone empty text nodes

### ISSUE THREAD

**Issue by bgotink** [PolymerLabs/lit-html#201]
In IE, the following works:

```ts
render(html`<div>0 ${1} ${2} 3</div>`, container);
assert.equals(container.innerHTML, '<div>0 1 2 3</div>');
```

and the following doesn't

```ts
render(html`<div>${1} ${2}</div>`, container);
assert.equals(container.innerHTML, '<div>1 2</div>');
```

IE11's `document.importNode` removes empty text nodes, which means the cloned template doesn't match the original template anymore, leading to random breakage when rendering lit-html templates.

The following code shows the problem:

```ts
const result = html`<div>${1} ${2}</div>`;

console.log('pre clone:');
const div = result.template.element.content.childNodes[0];
console.log(div.childNodes.length);
for (let i = 0; i < div.childNodes.length; i++) {
  console.log(div.childNodes[i], JSON.stringify(div.childNodes[i].nodeValue));
}

console.log('post clone:');
const clonedDiv = document.importNode(result.template.element.content, true).childNodes[0];
console.log(clonedDiv.childNodes.length);
for (let i = 0; i < clonedDiv.childNodes.length; i++) {
  console.log(clonedDiv.childNodes[i], JSON.stringify(clonedDiv.childNodes[i].nodeValue));
}

```

In Chrome it logs:

![image](https://user-images.githubusercontent.com/821510/33269537-5d5dc532-d381-11e7-83c2-f38d1f9de2ab.png)

In IE11 it logs:

![image](https://user-images.githubusercontent.com/821510/33277884-29bc5e96-d39a-11e7-96ca-cb0633dd3fb3.png)

Note: examples in typescript, which were run transpiled to a IE-compatible javascript.

EDIT: fixed typo in the test code which produced the screenshots: the `nodeValue`s of the original div's children were used instead of the clone's children.

**Comment by daKmoR** [comment]
awesome :) IE11 support :) nice :)
