### ISSUE TITLE
Page Blank on render

### ISSUE THREAD

**Issue by miki996** [PolymerLabs/lit-html#205]
Hi,

 I am not sure what I am doing wrong here but I am not getting any output in the browser. I am getting blank page.

This is the code i have. I am new to this framework and i need help to figure out how this works.

Any answer is welcomed.
`<html>

<head>

        <meta charset="utf-8"/>

        <script src="lit-html.js" type="module"></script>

        <script type="module">
              import { html, render } from './lit-html.js';
              
              const helloTemplate = (data) => html`
                <div class="module">
                  <h2>Hello ${data.name}!</h2>
                  <p>${data.content}</p>
                  </div>
              `;

              render(helloTemplate(data), document.body);
               </script>

</head>

<body>

    

</body>

</html>`

**Comment by obedm503** [comment]
any errors on the console?

**Comment by miki996** [comment]
Okay so this is my login.html file. I got these errors when i run the file on the node js local server.

![image](https://user-images.githubusercontent.com/23620141/33387909-c766c330-d52e-11e7-8dd3-cc438912e94e.png)

**Comment by miki996** [comment]
## I tried the code down which is copied from the github repository of the lit-html


![image](https://user-images.githubusercontent.com/23620141/33388735-0596b44c-d531-11e7-9b0b-9ef26bc85737.png)


And i got the following error while running the HTML file in node js local server
![image](https://user-images.githubusercontent.com/23620141/33388772-23224b7a-d531-11e7-8989-63381f61a378.png)


And finally when i change the type of the script from "module" to "text/javascript" i get the following error

![image](https://user-images.githubusercontent.com/23620141/33388848-5bb69310-d531-11e7-9f0a-d230c76309b1.png)

**Comment by bgotink** [comment]
The code in the first post yields an error in the console:

![image](https://user-images.githubusercontent.com/821510/33390419-25524526-d536-11e7-9481-b1855a28a5a3.png)

Some quick notes:

Modules always run in strict mode, so accessing undefined variables results in a TypeError. Defining the `data` property in the module or ensuring that the `data` property exists on the window makes the code work, e.g.:

```html
<!doctype html>
<html>

<head>
  <script type="text/javascript">
    window.data = { name: 'John Doe', content: 'This is an anonymous text' };
  </script>

  <script type="module">
    import { html, render } from './lit-html.js';

    const helloTemplate = (data) => html`
            <div class="module">
              <h2>Hello ${data.name}!</h2>
              <p>${data.content}</p>
              </div>
          `;

    render(helloTemplate(data), document.body);
  </script>
</head>

</html>
```

**Comment by obedm503** [comment]
this also got me in the past: native javascript modules require that you specify the extension of the file, so `./lit-html.js` instead of `'lit-html`

**Comment by miki996** [comment]
Thanks a lot for the answer. 

Now i cannot see any errors but how do i print something? 

Or how can i generate some data through lit-html so for example i can make login page?

Upon researching i cannot find any piece of tutorial or documentation to follow up

**Comment by miki996** [comment]
I still cannot run the HTML file. I cannot get anything printed out. This is run with the --disable-web-security in Chrome. Otherwise i had error for CORS policy.

![image](https://user-images.githubusercontent.com/23620141/33394510-ddadba5e-d542-11e7-9f6c-042fabcc811c.png)

**Comment by obedm503** [comment]
Are you loading it as `file://` or over http?

**Comment by obedm503** [comment]
just a recommendation: you probably don't need xampp when something like [`http-server`](https://www.npmjs.com/package/http-server) would sufice

**Comment by miki996** [comment]
Thanks. I'll keep that on my mind for the next time. 

Cheers!
