### ISSUE TITLE
build broken?

### ISSUE THREAD

**Issue by daKmoR** [PolymerLabs/lit-html#209]
```
git clone https://github.com/PolymerLabs/lit-html.git
cd lit-html
npm i
npm run build
```

results in 
```
$ npm run build

> lit-html@0.7.1 build /lit-html
> tsc

../../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.
```

if run directly you get "more" info...
```
$ tsc
../../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.
src/lib/repeat.ts(42,20): error TS2345: Argument of type '(part: NodePart) => any' is not assignable to parameter of type 'DirectiveFn'.
  Types of parameters 'part' and 'part' are incompatible.
    Type 'Part' is not assignable to type 'NodePart'.
      Property 'startNode' is missing in type 'Part'.
src/lib/unsafe-html.ts(24,53): error TS2345: Argument of type '(_part: NodePart) => DocumentFragment' is not assignable to parameter of type 'DirectiveFn'.
  Types of parameters '_part' and 'part' are incompatible.
    Type 'Part' is not assignable to type 'NodePart'.
src/lib/until.ts(21,15): error TS2345: Argument of type '(part: NodePart) => Promise<any>' is not assignable to parameter of type 'DirectiveFn'.
  Types of parameters 'part' and 'part' are incompatible.
    Type 'Part' is not assignable to type 'NodePart'.
src/test/lib/lit-extended_test.ts(128,11): error TS6133: 'event' is declared but its value is never read.
```

**Comment by bgotink** [comment]
The last batch of errors are TypeScript 2.6 related (see "--strictFunctionTypes" and "Write-only references now flagged as unused" in their [what's new](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html)).
These errors shouldn't arise if you use the typescript 2.4 found at `node_modules/.bin/npm`.

I don't get the `../../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.` error. Which version of npm are you using? If you're using a version that doesn't support the package-lock file you might be picking up a newer (breaking) version of a transitive dependency.

**Comment by daKmoR** [comment]
I'm on windows 10 with "Bash on Ubuntu on Windows"
and I could compile just file 2-3 weeks ago...

here some more details

```
$ npm --version
5.5.1
$ node --version
v8.6.0

$ ./node_modules/.bin/tsc --version
Version 2.4.1
$ ./node_modules/.bin/tsc
../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.

$ tsc --version
Version 2.6.2
$ tsc
// errors from original post +
../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.
```

I also asked a friend who is using debian + node 6 and he has the same error `../../node_modules/@types/temp/index.d.ts(8,23): error TS2307: Cannot find module '.'.`

:/

**Comment by bgotink** [comment]
The `@types/temp` package doesn't even get installed on my fresh clone, even if I remove `package-lock.json` or if I run `npm cache clean --force` before installing. Removing the lockfile does update typescript to 2.6 so the build does break without lockfile.
Could you take a look with `npm ls` to find out why the package gets installed?

I'm using macOS with node 8.9.0 and npm 5.5.1.

**Comment by daKmoR** [comment]
OMG...

I worked in `/html/lit-html` and for some testing a had a `/html/node_modules` folder...

so it was
```
/html/
  node_modules/
  lit-html/
    node_modules/
    lit-html.js
    ...
```

and that apparently mixed everything up? my WTF moment of the month :/

@bgotink thx for sticking with me :)
