### ISSUE TITLE
Distribute minified file

### ISSUE THREAD

**Issue by aaronshaf** [PolymerLabs/lit-html#216]

**Comment by justinfagnani** [comment]
The current plan is to only publish one canonical version of lit-html - the unbundled, unminified module source - to prevent applications importing multiple versions from different paths and getting code duplication. Applications can bundle, compile, minify, etc. as needed.

**Comment by aaronshaf** [comment]
What about those of us that want to import this lib via [unpkg](https://unpkg.com/lit-html@0.7.1/), or some other CDN?
