### ISSUE TITLE
Evaluate expressions inside html attributes

### ISSUE THREAD

**Issue by kolis** [PolymerLabs/lit-html#234]
I want to dynamically assign a class to a dom node, eg
```html
<span class="${this.someFlag ? "foo" : "bar"}">${someText}</span>
```

But I'm not getting any class assigned. What am I doing wrong?

**Comment by daKmoR** [comment]
are u using lit extended?
then u would need `class$="..."`

or maybe this helps

```

${this.someFlag ? html`foo` : htm`bar`}

```

**Comment by kolis** [comment]
Aha, yes I'm using lit-extended. I was not aware of this syntax, thanks for the response. I would suggest hosting the html docs someplace publically, and providing some links from the main Readme.md.

I had not seen `modules/_lib_lit_extended_.html` !
