### ISSUE TITLE
Setter in child component not called if component in own module

### ISSUE THREAD

**Issue by rogeru** [PolymerLabs/lit-html#237]
In the example below```this.shadowRoot.querySelector('my-fruit').froot = this.fruit;``` sets property ```froot``` on the child component, but its setter is not called.

If including both components in a single module, or if moving the MyFruit component above MyApp, then the setter is called fine.

Is this a bug? If not what is the explanation of this?

```
<!DOCTYPE html>
<html>
  <head>
    <script type="module">
      import {html, render} from '//unpkg.com/lit-html/lib/lit-extended';
      class MyApp extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({mode: 'open'});
        }
        connectedCallback() {
          this.fruit = 'apple';
        }
        get fruit() { return this._fruit; }
        set fruit(v) { this._fruit = v; this.invalidate(); }
        change() {
          this.fruit = this.shadowRoot.querySelector('#new').value;
          this.shadowRoot.querySelector('#new').value = '';
          this.shadowRoot.querySelector('my-fruit').froot = this.fruit;
        }
        render() {
          return html`
            <p>Fruit in parent: ${this.fruit}</p>
            <my-fruit froot="${this.fruit}"></my-fruit>
            <input id="new" type="text"/>
            <button on-click="${() => this.change()}">Change</button
          `;
        }
        invalidate() {
          if (!this.needsRender) {
            this.needsRender = true;
            Promise.resolve().then(() => {
              this.needsRender = false;
              render(this.render(), this.shadowRoot);
            });
          }
        }
      }
      customElements.define('my-app', MyApp);
    </script>

    <script type="module">
      import {html, render} from '//unpkg.com/lit-html/lib/lit-extended';
      class MyFruit extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({mode: 'open'});
        }
        connectedCallback() {
          this.invalidate();
        }
        get froot() { return this._froot; }
        set froot(v) { this._froot = v; this.invalidate(); }
        render() {
          return html`<p>Fruit in child: ${this.froot}</p>`;
        }
        invalidate() {
          if (!this.needsRender) {
            this.needsRender = true;
            Promise.resolve().then(() => {
              this.needsRender = false;
              render(this.render(), this.shadowRoot);
            });
          }
        }
      }
      customElements.define('my-fruit', MyFruit);
    </script>
  </head>
  <body>
    <my-app></my-app>
  </body>
</html>
```

**Comment by LarsDenBakker** [comment]
@rogeru perhaps you're running into async issues. Module scripts are non-blocking, and by placing them both in a separate script one might run before the other.

Try checking the constructor of the child element at the moment of setting the property. If the constructor is HTMLElement, the custom element definition was not loaded yet.

**Comment by rogeru** [comment]
The property is being set when clicking the button, so way later at which point both modules have been loaded. 

```this.shadowRoot.querySelector('my-fruit').froot = this.fruit;```

**Comment by bgotink** [comment]
If you ensure that the `my-fruit` definition is loaded before `my-app`, it works.

This is more or less what happens:

1. `my-app` is upgraded, it's connectedCallback is called
2. `my-app` renders
    * `my-fruit` is not upgraded, its `froot` property is set to `"apple"`
3. `my-fruit` is upgraded, the `froot` property on the instance now shadows the property on the MyFruit prototype
4. Some time later: the button is clicked, the `froot` property is set on the instance, but the prototype's setter is never called as the instance property shadows the `froot` property of the prototype.

When `my-fruit` is loaded before `my-app`, this is what happens:

1. `my-app` is upgraded, it's connectedCallback is called
2. `my-app` renders
    * `my-fruit` is created as `MyFruit`, so the `froot` setter is called
3. Some time later: the button is clicked, the `froot` property setter is called as expected

To verify this is truly what's going on:

- run `document.querySelector('my-app').shadowRoot.querySelector('my-fruit').hasOwnProperty('froot')`, you'll see it's `true`
- run `console.log(this.shadowRoot.querySelector('my-fruit').constructor);` after `render()` in `MyApp#invalidate` and you'll see `ƒ HTMLElement() { [native code] }` after the initial render

If you ensure that `MyFruit` is loaded before `MyApp`, you'll see `false` and `class MyFruit extends HTMLElement { ... }`

**Comment by rogeru** [comment]
Thanks @bgotink that makes sense.

What is the suggested solution to set a property on a child component as in the example above?

1. ensure the child component is loaded first
2. remove the ```froot="${this.fruit}"``` from the parent html and initialize child's froot property programmatically in the connectedCallback via a timeout, e.g.
```
        connectedCallback() {
          this.fruit = 'apple';
          setTimeout(() => {
            this.shadowRoot.querySelector('my-fruit').froot = this.fruit;
          }, 0);
        }
```
3. Use an attribute instead of a property. But in that case froot could not be an object.

**Comment by kenchris** [comment]
You can make the render only render when they are defined. You can check customElements, I think I have an example somewhere

**Comment by kenchris** [comment]
Copied from another project 

```
Promise.all([
            customElements.whenDefined('fiber-demo'),
            customElements.whenDefined('fiber-triangle'),
            customElements.whenDefined('fiber-dot')
        ]).then(_ => {
            requestAnimationFrame(update);
        });
```

**Comment by rogeru** [comment]
Thanks @kenchris works great. Here is the full example for reference. I'll close this issue then.

```
<!DOCTYPE html>
<html>
  <head>
    <script type="module">
      import {html, render} from '//unpkg.com/lit-html/lib/lit-extended';
      class MyApp extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({mode: 'open'});
        }
        connectedCallback() {
          this.fruit = 'apple';
        }
        get fruit() { return this._fruit; }
        set fruit(v) { this._fruit = v; this.invalidate(); }
        change() {
          this.fruit = this.shadowRoot.querySelector('#new').value;
          this.shadowRoot.querySelector('#new').value = '';
          this.shadowRoot.querySelector('my-fruit').froot = this.fruit;
        }
        render() {
          return html`
            <p>Fruit in parent: ${this.fruit}</p>
            <my-fruit froot="${this.fruit}"></my-fruit>
            <input id="new" type="text"/>
            <button on-click="${() => this.change()}">Change</button
          `;
        }
        invalidate() {
          if (!this.needsRender) {
            this.needsRender = true;
            Promise.resolve(customElements.whenDefined('my-fruit'))
              .then(() => {
                this.needsRender = false;
                render(this.render(), this.shadowRoot);
              });
          }
        }
      }
      customElements.define('my-app', MyApp);
    </script>

    <script type="module">
      import {html, render} from '//unpkg.com/lit-html/lib/lit-extended';
      class MyFruit extends HTMLElement {
        constructor() {
          super();
          this.attachShadow({mode: 'open'});
        }
        connectedCallback() {
          this.invalidate();
        }
        get froot() { return this._froot; }
        set froot(v) { this._froot = v; this.invalidate(); }
        render() {
          return html`<p>Fruit in child: ${this.froot}</p>`;
        }
        invalidate() {
          if (!this.needsRender) {
            this.needsRender = true;
            Promise.resolve().then(() => {
              this.needsRender = false;
              render(this.render(), this.shadowRoot);
            });
          }
        }
      }
      customElements.define('my-fruit', MyFruit);
    </script>
  </head>
  <body>
    <my-app></my-app>
  </body>
</html>
```
