### ISSUE TITLE
Render DOM from a function call

### ISSUE THREAD

**Issue by lastmjs** [PolymerLabs/lit-html#25]
I'm wondering how to get something as simple as the following to work:

```
render(html`
            ${() => {
                return `<div>Hello</div>`;
            }}
`, document.getElementById('render-area'));
```

I would like the `div` to actually be a DOM div, but it just returns a string and renders as a literal string. Am I missing something simple? This will also help me figure out how to do lists like `dom-repeat` or how JSX does them. Thanks.

**Comment by lastmjs** [comment]
Hold on, I think I got it. I need to use the `html` function to return an object that lit-html can use to create DOM. Excellent!

**Comment by justinfagnani** [comment]
Glad you got it figured out! This is super new, so the docs are all written by me and not clear enough yet. This is good feedback on where to improve.

**Comment by justinfagnani** [comment]
Also, check out src/lib/repeat.ts, which implements an efficient, recycling repeat directive
