### ISSUE TITLE
Adding functions to events seems to be executed immediately

### ISSUE THREAD

**Issue by charlike** [PolymerLabs/lit-html#26]
Hi! :100: 

I'm trying this lib, and in first look it seems fantastic and works. Works, but almost. It's seems that when attach an event handler it is executed immediately. For example setting a function on `onclick` event is called on render, not when element is clicked.

```js
const msg = 'Hello!'
const Main = () => html`<main>
  <h1>${msg}!</h1>
  <button onclick=${() => {  console.log('woohoo') }}>+1</button>
</main>`

render(Main(), document.body)
```

http://jsbin.com/sogitix/28/edit?js,console,output

**Comment by justinfagnani** [comment]
Because functions are used as extension points (function values are called with the Part object for an expression so that it can imperatively modify the Part), values that are intended to be functions, like event handlers must be returned from a wrapper function:

```js
html`<main>
  <h1>${msg}!</h1>
  <button onclick=${_=> () => {  console.log('woohoo') }}>+1</button>
</main>`
```

Also, make sure you're using lit-extended, because core lit-html only sets attributes, which means the function would be converted to a string.

**Comment by justinfagnani** [comment]
This is talked about a little bit here, though could clearly use some more detail: https://github.com/PolymerLabs/lit-html#function-values

**Comment by charlike** [comment]
> This is talked about a little bit here

Link don't work, the anchor :D nevermind, found it and probably make sense to show above example to clarify the things.

> make sure you're using lit-extended

hearing it for the first time

> values that are intended to be functions, like event handlers must be returned from a wrapper function:

Wouldn't it be better to switch the places. So if that function returns a function use it like now, so when someone don't care about parts and etc he will be able to pass normal function.


for example
```js
html`<main>
  <h1>${msg}!</h1>
  <button onclick=${clicked}>+1</button>
</main>`

function clicked (evt) {
  console.log('woo hoo, called when clicked'
  // if it returns a function then use it as currently
  return (part) => part.setValue((part.previousValue + 1) || 0)
}
```

**Comment by justinfagnani** [comment]
> Wouldn't it be better to switch the places. So if that function returns a function use it like now, so when someone don't care about parts and etc he will be able to pass normal function.

Yeah, and I filed #29 for it. I'll try to get it done asap

**Comment by charlike** [comment]
Hooo!! :tada: Awesome! :clap: 

So i believe it will fix this issue too, or I _must_ use `lit-extended`? And if i must, should i include and the core too?

**Comment by justinfagnani** [comment]
Well, to write to properties instead of attributes you need to use lit-extended - because that's a pretty opinionated default

**Comment by justinfagnani** [comment]
I'm going to close this as working-as-intended for now, but I'll change the behavior in #29. Thanks for the report!

**Comment by justinfagnani** [comment]
Also, you need to import `html` from `lit-html.js` and `render` from `lit-extended.js` for now... I'll revisit re-exporting `html` from lit-extended soon.

**Comment by charlike** [comment]
Great, great, thanks for the tip. :wink:
