### ISSUE TITLE
Event handler context incorrect

### ISSUE THREAD

**Issue by lastmjs** [PolymerLabs/lit-html#28]
Here's some example code:

```
import {html} from './node_modules/lit-html/lib/lit-html';
import {render} from './node_modules/lit-html/lib/labs/lit-extended';

class TestElement extends HTMLElement {
    connectedCallback() {
        render(html`
            <button onclick="${() => this.buttonClick}">Property listener</button>
            <button on-click="${() => this.buttonClick}">Custom syntax listener</button>
        `, this);
    }

    buttonClick() {
        this.helloWorld();
    }

    helloWorld() {
        console.log('Hello world!');
    }
}

window.customElements.define('test-element', TestElement);
```

If you click either of the buttons, `buttonClick` is invoked, but the context is set to the button, and not to the host component. Obviously this does not allow `this.helloWorld` to be called.

**Comment by lastmjs** [comment]
I can get around it by binding, but not ideal of course:

```
import {html} from './node_modules/lit-html/lib/lit-html';
import {render} from './node_modules/lit-html/lib/labs/lit-extended';

class TestElement extends HTMLElement {
    connectedCallback() {
        render(html`
            <button onclick="${() => this.buttonClick.bind(this)}">Property listener</button>
            <button on-click="${() => this.buttonClick.bind(this)}">Custom syntax listener</button>
        `, this);
    }

    buttonClick() {
        this.helloWorld();
    }

    helloWorld() {
        console.log('Hello world!');
    }
}

window.customElements.define('test-element', TestElement);
```

**Comment by justinfagnani** [comment]
lit-extended doesn't do anything with the context, it just calls addEventListener, which will set the `this` reference to the target element. Since you already have an arrow function which captures the elements `this` reference, just pass the arrow function and `this` won't be reset:

```
<button onclick="${_=> (e) => this.buttonClick(e)}">Property listener</button>
```

**Comment by lastmjs** [comment]
I see...that seems like undesired and unexpected behavior though. When would you ever want the listener's context to be the element it's defined on? Polymer doesn't seem to work this way (I know under the hood it's different).

**Comment by lastmjs** [comment]
Also, why does lit call addEventListener? Can't the literal onclick property just be set?

**Comment by justinfagnani** [comment]
This is how the platform works - when a listener is called, it's `this` reference is set to the target element. Arrow functions capture the lexical `this` and give a nice way out of that behavior.

As for `addEventListener`:

- it's a much more generic API and works in all cases
- Not all events have `on*` handler properties defined for them, especially if you want to use bubbling, you may be listening for an event that's defined on a descendant.
- addEventListener() allows for more than one handler
- on* handlers are surprisingly tricky to write correctly
- Custom elements typically don't implement on* handlers for events they fire.

**Comment by justinfagnani** [comment]
Ok, I hope that explanation was good. Maybe I can copy it to docs.

btw, you can still use on* handlers, since nothing is preventing you from doing so. You will need lit-extended to get property support.

Also, I think I'm going to try to make using functions values simpler with #29
