### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by lastmjs** [PolymerLabs/lit-html#30]
I've got this CSS variable I'm trying to use from within a template literal:

```
:host {
    --box-shadow: 0px 0px 1px black;
}
```

The variable is not applied to the host element when inspecting it with the Chrome dev tools.

**Comment by justinfagnani** [comment]
It works for me in the main document if I use the `:root` selector. How are you setting up the shadow root?

**Comment by lastmjs** [comment]
I didn't set up a shadowRoot after switching over from Polymer 2, that's probably the problem. Sorry about that.
