### ISSUE TITLE
CSS containment

### ISSUE THREAD

**Issue by kenchris** [PolymerLabs/lit-html#37]
There was a drive to enable some good default for CSS containment for custom elements and element in general, but it was rejected as far as I recall, due to backwards compatibility.

Maybe it makes sense to reconsider that for lit html?

**Comment by justinfagnani** [comment]
I think that's something of a concern for the component layer that would presumably sit above lit-html.

Right now, I see styles handling remaining the same - as style element in the shadow root. That does mean that if an element want to turn on containment, they have to do it in `:host` rules like:

```js
class MyElement extends LitMixin(HTMLElement) {
  render() {
    return html`
      <style>
        :host {
          contain: strict;
        }
      </style>
    `;
  }
}
```

**Comment by kenchris** [comment]
Yes, I get how to accomplish it. My worry is that very few developers know about CSS containment, and thus don't use it at all, so it would be nice if a framework like Polymer, could help provide good defaults and educate developers about it.

**Comment by justinfagnani** [comment]
Oh, sure. lit-html isn't trying to be anything close to a framework though, just a way to render and update DOM.

As an advantage over Polymer templates, this enables easy inheritance/composition, so we can include base styles:

```js
class MyElement extends LitMixin(HTMLElement) {
  render() {
    return html`
      ${this.baseStyle}
      <style>
        :host {
          // element styles
        }
      </style>
    `;
  }
}
```

Where `this.baseStyle` adds containment.

**Comment by justinfagnani** [comment]
I'm going to close as not in scope for now. Once we build layers on top we should definitely think of this. cc @sorvell
