### ISSUE TITLE
Wrong description in readme

### ISSUE THREAD

**Issue by kenchris** [PolymerLabs/lit-html#38]
```
render() takes a TemplateResult and renders it to a DOM container. On the initial render it clones the template, then walks it using the remembered placeholder positions, to create Parts.
```

Actually html() created the Template which calls _parse and does the walking

**Comment by justinfagnani** [comment]
I think the current description is accurate.

`html` creates the `Template`, and it does a walk to find what are called `TemplatePart`s, but `render()` also does a walk to find the instantiated placeholders and make `Part`s (which are separate from `TemplatePart`s).

The way to think of this is: TemplatePart is to Template as Part is to Instance

**Comment by kenchris** [comment]
Yes, you are right.

I changed the description a bit in my slides. Also to explain the insertion of the two text nodes. I think the steps are a bit clearer there (at least to me) so if you like the changes, feel free to reuse.

I think what was most interesting to me was how the updating works, which is what I found less described in the readme.

**Comment by justinfagnani** [comment]
Which part of updating? How the placeholder nodes are inserted and found?

I should probably have a separate doc file with just the description on how things work.
