### ISSUE TITLE
Template containing growing list can cause younger siblings to disappear

### ISSUE THREAD

**Issue by cdata** [PolymerLabs/lit-html#51]
When re-rendering a template that contains a list that is growing, it is possible to cause younger siblings to disappear. Please refer to this reduced test case for an example: [https://glitch.com/edit/#!/futuristic-color?path=x-example.js](https://glitch.com/edit/#!/futuristic-color?path=x-example.js).

**Comment by justinfagnani** [comment]
Fixed in #46
