### ISSUE TITLE
Elements receive zero-th property part value for all properties

### ISSUE THREAD

**Issue by cdata** [PolymerLabs/lit-html#54]
Please consider this reduced test case and check the console: https://glitch.com/edit/#!/tremendous-jeep?path=x-example.js:12:75

### What I expected

```
Element props follow: foo="foo" bar="bar" disabled="true"
```

### What I got

```
Element props follow: foo="foo" bar="foo" disabled="foo"
```

**Comment by justinfagnani** [comment]
Fixed in #55
