### ISSUE TITLE
Question: How to handle render inheritance?

### ISSUE THREAD

**Issue by jimsimon** [PolymerLabs/lit-html#59]
What's the proper way to handle inheritance with this library?

Multiple:
```js
class Base {
  render () {
    return html`<div></div>`
  }
}

class Derived extends Base {
  render () {
    return html`<span>${super.render()}</span>`
  }
}

const derived = new Derived()
render(derived.render(), document.body) // lit-html's render
```

Single v1:
```js
class Base {
  render () {
    return `<div></div>`
  }
}

class Derived extends Base {
  render () {
    return html`<span>${super.render()}</span>`
  }
}

const derived = new Derived()
render(derived.render(), document.body) // lit-html's render
```

Single v2:
```js
class Base {
  render () {
    return `<div></div>`
  }
}

class Derived extends Base {
  render () {
    return `<span>${super.render()}</span>`
  }
}

const derived = new Derived()
render(html`${derived.render()}`, document.body) // lit-html's render
```

Now that I think about it, I suspect that the multiple example won't actually work, but would love some confirmation.

**Comment by jimsimon** [comment]
In case it's not immediately clear: the multiple example uses the `html` template tag in each class's render function, the single v1 example only uses it at the end of the inheritance chain, and the single v2 example only uses it at the final render call.

**Comment by justinfagnani** [comment]
Good question. The "Multiple" example is the correct way do compose templates. A string without a `html` tag is just a string, and would be rendered as text, not HTML (it would render the text "<div></div>", not an empty <div>).

I think this becomes more clear when you have more complex templates with expressions. If you didn't tag them with `html`, they'd be strings with embedded values that aren't efficiently updatable.

**Comment by jimsimon** [comment]
Ah okay, that makes sense.  If I'm understanding this correctly, the `super.render()` call in the "multiple" example would end up as a Part right?  In which case lit-html would detect that it's a template TemplateResult and handle it accordingly I think.

Thanks for the quick reply :)

**Comment by justinfagnani** [comment]
That's exactly correct :)

You're welcome!
