### ISSUE TITLE
Beginners question (probably)

### ISSUE THREAD

**Issue by JohnGorter** [PolymerLabs/lit-html#60]
When copying and pasting in the examples into an html file and running it in a browser (chrome version 60) and of course linking to the transpiled version (lit-html.js). Chrome reports errors about the export keyword not being recognized.. (SyntaxError: Unexpected token export)..

Even when running it in NodeJS by just require('lit-html') after npm installing it shows this same error... 

What am I missing here?

**Comment by nicolasparada** [comment]
You will need Chrome 61 and `<script type=module>`.

**Comment by Pesthuf** [comment]
You can also use a module bundler like Webpack or Rollup.
That way, it will work in any browser.

**Comment by JohnGorter** [comment]
Tried that with webpack with no success. Could that be because the tsconfig for lit-html is set to target es2017?

**Comment by nicolasparada** [comment]
Maybe lit-html should not publish those src files (ts, build config) to npm.

**Comment by justinfagnani** [comment]
@JohnGorter can you share your webpack config? Webpack should be able to handle standard ES6 I hope.

@nicolasparada I can remove the .ts files from npm

**Comment by esbenjuul** [comment]
I have the same problem with webpack only running babel es2015.

**Comment by JohnGorter** [comment]
try to post it tomorrow.. away from work now... sorry.

**Comment by justinfagnani** [comment]
Module support is spreading, so this should be easier to try out. Please repopen is we need further details on using modules.
