### ISSUE TITLE
IE / Edge are weakly supported

### ISSUE THREAD

**Issue by WebReflection** [PolymerLabs/lit-html#61]
Try the following on any IE / Edge browser.
```js
render(
  html`<i data-i="${'a'}" class="${'b'}"></i>`,
  document.body
);
document.body.appendChild(
  document.createTextNode(
    document.body.firstElementChild.outerHTML
  )
);
```

**Expected layout**
```
<i data-i="a" class="b"></i>
```

**Current layout**
```
<i class="a" data-i="b"></i>
```
![screenshot from 2017-08-23 15-05-18](https://user-images.githubusercontent.com/85749/29620161-1364140c-8815-11e7-8fde-69af4d80679c.png)

FYI this is fixed in `hyperHTML` since v0 and Firefox used to have the same issue.

**Comment by WebReflection** [comment]
is this still the case?

**Comment by jridgewell** [comment]
This was fixed by https://github.com/PolymerLabs/lit-html/pull/132.
