### ISSUE TITLE
Content not too reliable

### ISSUE THREAD

**Issue by WebReflection** [PolymerLabs/lit-html#62]
As described in [this comparison point](https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b#gistcomment-2183300) it's very easy to mislead lit-html parser.

```js
render(
  html`a{{}}b${'c'}d`,
  document.body
);
```

**Comment by KeithHenry** [comment]
I think the cause of this is: https://github.com/PolymerLabs/lit-html/blob/2dab86c0ac55825df7a6f98796135c4c45b0b818/src/lit-html.ts#L78

This means `{{}}` outside of a `${}` becomes a placeholder for a part.

It's easy to change, but that just moves the problem.

**Comment by WebReflection** [comment]
I haven't used that string by accident, I know that's the issue :smile: 

You can either use something different, moving the problem, or look how other projects already solved the issue :wink:

**Comment by WebReflection** [comment]
I use comments, not text, so I have also many other advantages.

**Comment by KeithHenry** [comment]
Yes, I noticed that. Do you not find that creates additional issues for parts in certain attributes?

**Comment by WebReflection** [comment]
> Do you not find that creates additional issues ...

quite the opposite, it solves all the issues if you don't allow attributes without quotes (v0) while it just need simple sanitization if you don't (v1).

So, attributes, are fine, the content thought, comments are magic there, way more powerful than text.

They will switch to comments for content at some point, I'm pretty sure about it :wink:
