### ISSUE TITLE
Unable to remove a listener

### ISSUE THREAD

**Issue by WebReflection** [PolymerLabs/lit-html#63]
[This line](https://github.com/PolymerLabs/lit-html/blob/2dab86c0ac55825df7a6f98796135c4c45b0b818/src/lib/lit-extended.ts#L102) makes it impossible to reach the `listener === undefined` one.

Apparently there are no tests to cover listeners (add/remove) in the extended version.

**Comment by jimsimon** [comment]
I was trying to write some tests and a fix for this, but I'm finding that `EventPart.setValue` is actually only ever called the first time I render.  Maybe my test setup is wrong, but I'm doing:

```js
render(html`<button on-click=${clickHandler}>foo</button>`, container);
render(html`<button>foo</button>`, container);
```

My guess is that this is happening because the second `render` call doesn't have any `values`?

**Comment by jimsimon** [comment]
I was able to trigger the error condition by doing: 

```js
render(html`<button on-click=${clickHandler}>foo</button>`, container);
clickHandler = undefined
render(html`<button on-click=${clickHandler}>foo</button>`, container);
```

After playing around with it a little more, I suspect that it's seeing my original attempt as a new template, so it's re-rendering the entire button again.
