### ISSUE TITLE
Should placeholders be comments rather than strings?

### ISSUE THREAD

**Issue by KeithHenry** [PolymerLabs/lit-html#68]
Discussion started in https://github.com/PolymerLabs/lit-html/issues/62 and from looking at a similar approach in https://github.com/WebReflection/hyperHTML/blob/3fec9d55835b90cf337f24264880c580e14f71e3/hyperhtml.js#L78-L79

There the placeholders are comments, rather than strings. There are advantages to using comments in terms of DOM changes and the like, but additional handling required for attributes.

Is this a change worth making here too?

**Comment by justinfagnani** [comment]
I like strings because they work better with attributes. I have a fix for the table issue that uses comments just in some placese.

**Comment by justinfagnani** [comment]
See #74 

Assuming that PR works out, comments will be used for text positions and text will be used for most attribute positions. I'm going to close this issue now as it's covered by #62 and #64.
