### ISSUE TITLE
Problem with event subscription when not using fat arrow syntax (lit-extended)

### ISSUE THREAD

**Issue by nborelli** [PolymerLabs/lit-html#76]
Version: **lit-html@0.6.0-pre.3**  - lit-extended

If I subscribe to an event like this everything works great:

WORKS: `<button on-click=${ e => this._reverseClicked(e) }>Reverse</button>`
DOES NOT WORK:  `<button on-click=${ this._reverseClicked }>Reverse</button>`

However, if I use the abbreviated syntax because I do not care about the event, this will be undefined and I will get an error.   Here is my very complicated reverse function for reference:

`
_reverseClicked(event) {
      this.message = this.message.split('').reverse().join('');
 }
`

Obviously, I will stick with the fat arrow syntax for now.

**Comment by stramel** [comment]
I think you need to bind the `this` context? Maybe?

**Comment by nborelli** [comment]
You are correct that `<button on-click=${this._reverseClicked.bind(this)}>Reverse</button>` works, but that sure feels pretty ugly to me. At that point, I believe people would just use the fat arrow syntax for readability alone.

I believe LIT Extended should just do this automatically if we pass a reference to a function that is defined in our class.

**Comment by gdi2290** [comment]
this is the same problem as React. React had auto bind when using createClass but removed it due to the preferred ES6 format. lit-html shouldn't have to do anything here as that's a concern

**Comment by justinfagnani** [comment]
Agreed with @gdi2290. Auto-bind is also difficult to do here becuase lit-html does not presume any component model, so there's nothing to bind _to_.

I think the best way to do this is going to be to define handlers as instance properties:

```ts
class MyElement extends LitElement {
  private _clickHandler: (e) => { this.doStuff(); }

  render() {
    return html`<button on-click=${this._clickHandler}>Click Me</button>`;
  }
}
```

**Comment by nborelli** [comment]
One hack that makes it work is to do the following:

    html(strings, ...values) {
        for(let i=0;  i < values.length; i++) {
            if (typeof values[i] === 'function') {
                values[i] = values[i].bind(this);
            }
        }

        return html.call(this, strings, ...values);
    }

And then instead of using the **html** type template literal function, you would uses **this.html**

This allows the function to know the "this" context, but feels a little hacky.

**Comment by gdi2290** [comment]
I think the only thing lit-html should do is just mention this in the readme since it's just a javascript gotcha

**Comment by justinfagnani** [comment]
Good point, let's treat this bug as an issue for that.

**Comment by nborelli** [comment]
Hi @justinfagnani and @gdi2290,

Yeah, you guys are probably right, I was just looking for a ways to make the syntax a bit easier.  Just of completeness, I gave the idea I proposed above a little more thought and cleaned up the `html` instance method I proposed above as:

```javascript
html(strings, ...values) {
    values = values.map(v => (typeof v === 'function' && v.name && this[v.name] === v) ? v.bind(this) : v);
    return html.call(this, strings, ...values);
}
```

One possibility would be to pass this function as an argument into the `render()` function so that you would have:

```javascript
render(html) {
    return html`<button on-click=${this._reverseClicked}>Reverse</button>`;
}
```

This also means that the component writers will not have to import the `html` function from lit-html at all as we pass it to the `render()` function.  I don't know if this sort of thing would make writing the editor add-ins and tooling harder though.

OK, letting it go now...

**Comment by justinfagnani** [comment]
Closing this issue in favor of one explicitly for documentation.

**Comment by js-choi** [comment]
Cf. [the ECMAScript bind-operator syntax proposal](https://github.com/tc39/proposal-bind-operator), which would allow turning `<button on-click=${this._reverseClicked.bind(this)}>Reverse</button>` into the more compact `<button on-click=${this::_reverseClicked}>Reverse</button>`, but which also would not be implemented for another several years.
