### ISSUE TITLE
Add src/ to .npmignore

### ISSUE THREAD

**Issue by justinfagnani** [PolymerLabs/lit-html#83]
We're publishing the .ts files to npm because of the empty .npmignore

**Comment by justinfagnani** [comment]
Actually... including /src/ makes the source maps works for consumers. Including the source shouldn't be causing a problem.

**Comment by gdi2290** [comment]
how about?
    "sourceMap": true,
    "inlineSources": true
https://www.typescriptlang.org/docs/handbook/compiler-options.html
