### ISSUE TITLE
Using "className" attribute instead of "class" for dynamic classes is unclear

### ISSUE THREAD

**Issue by Lodin** [PolymerLabs/lit-html#97]
I have found that if I want to set class attribute dynamically, I have to use `className` instead of `class` while static classes should be defined as `class`.

```javascript
html`
  <div className=${'test'}>
    <div class="test2"></div>
  </div>
`
```

I've prepared a test case for it, but it is untested, because I failed to start tests on my Windows. 
```javascript
test('renders class', () => {
  const container = document.createElement('div');
  const container2 = document.createElement('div');
  const t = html`<div class="${'test'}"></div>`;
  const t2 = html`<div className="${'test'}"></div>`;
  render(t, container);
  render(t2, container2);
  const div = container.firstElementChild!;
  const div2 = container2.firstElementChild!;
  assert.equal(div.className, '');
  assert.equal(div2.className, 'test');
});
```

Also you can see this problem in my ["lit-html" version](https://github.com/Lodin/js-framework-benchmark/tree/lit-html/lit-html-v0.6.0-keyed) for `js-framework-benchmark`. The code is following: 

[main.js, line 168](https://github.com/Lodin/js-framework-benchmark/blob/lit-html/lit-html-v0.6.0-keyed/src/main.js#L168)
```javascript
render(html`${this.store.data.map(i => html`
  <tr className="${i.id === this.store.selected ? 'danger' : ''}">
    ...other code
  </tr>`
)}`, this.tbody);
```
If I replace `className` in this code with `class`, it will never change `<tr>`'s class.

**Comment by justinfagnani** [comment]
Since you're using lit-extended, which sets properties by default, you have to set the class attribute via an explicit attribute binding, like: `<div class$=${'test'}>`

**Comment by Lodin** [comment]
Thanks for the explanation, I've understood the difference.
