### ISSUE TITLE
avoid future merge commits

### ISSUE THREAD

**Issue by gdi2290** [PolymerLabs/lit-html#98]
<img width="771" alt="screen shot 2017-09-06 at 1 23 49 pm" src="https://user-images.githubusercontent.com/1016365/30132841-aaa84d5a-9306-11e7-8b11-9536837108ea.png">
it would be better to view git history if merge commits were avoided. You can still use rebase merging or squash merging

**Comment by justinfagnani** [comment]
Good idea. Done.
